### ISSUE TITLE
Campaigns - full width overview

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_campaigns#28]
On https://localgovdrupal.agile.coop/node/28/edit

Under "Banner image and colours", the "full width overview" checkbox option is in the wrong place

Let's discuss:

- moving it to "child pages"
- put above the page list
- rename as "show page menu" (default to unchecked, not showing menu)

**Comment by stephen-cox** [comment]
Hi @willguv,

Just looking at fixing this. I agree the checkbox is in the wrong place, but I'm not convinced child pages is the best place for it. That's because it only hides the menu on the overview pages. Is this correct or should it hide the menu for both campaign overview and standard pages? 

If it should only hide the menu on campaign overviews then I suggest moving to the description tab as adding it to child pages will be confusing. What do you think?

Thanks,

Stephen

**Comment by willguv** [comment]
Hi @stephen-cox the idea is the checkbox toggles right hand menus on/ off for the entire campaign, so campaign overview and child campaign pages
